### ISSUE TITLE
Filters

### ISSUE THREAD

**Issue by Phoscur** [konstantinkrassmann/ngCordova-nfc#4]
https://github.com/don/ionic-nfc-reader/blob/master/www/js/filters.js
Defines some nice angular filters for tag decoding, how can I access those with this module?
Maybe it's a good idea to add them to this module?
I aim to keep my own code clean of window.nfc calls, on the otherside, I'm not really sure I need those filters..

**Comment by Phoscur** [comment]
Well reading documentation again, I see I find those under $cordovaNfcUtil, so it's probably fine, maybe consider also adding an angular filter equivalent..

**Comment by konstantinkrassmann** [comment]
This is just a cover for https://github.com/chariotsolutions/phonegap-nfc, no additional features planned.
