### ISSUE TITLE
Use in Ionic

### ISSUE THREAD

**Issue by vinimendes3** [konstantinkrassmann/ngCordova-nfc#9]
Has someone already used in Ionic instead of PhoneGap? Does it works?

I'm trying in Ionic but the methods of listener are not called when I touch a NFC tag behind my phone.

I only want to read the ID of the tag.

Thanks in advance...

**Comment by konstantinkrassmann** [comment]
i'm using it in a ionic project. 

Can you give me code example ?

**Comment by ruisilva450** [comment]
You have this [repo](https://github.com/don/ionic-nfc-reader). Credits to [@don](https://github.com/don)

**Comment by vinimendes3** [comment]
After some different tests, it is already working! :D Thanks @konstantinkrassmann and @ruisilva450
